
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module LEON3_DE2115(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,

	//////////// LED //////////
	output		     [8:0]		LEDG,
	output		    [17:0]		LEDR,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		    [17:0]		SW,

	//////////// GPIO, GPIO connect to GPIO Default //////////
	inout 		    [35:0]		GPIO
);

   wire [7:0] 				gpio;
   wire 					dsutx;
   wire 					dsurx;
   wire 					rxd1;
   wire 					txd1;
   wire [3:0] 				triggerout;
   wire 					wdogn;

	leon3mp top(.clk   (CLOCK_50),
		    .resetn(KEY[3]),
		    .errorn(led8inv),
		    .DebugUart_tx (dsutx),
		    .DebugUart_rx (dsurx),
		    .dsuact(LEDR[17]),
			 .dsuen(SW[17]),
			 .dsubre (SW[16]),
		    .PeriphUart_rx  (rxd1),
		    .PeriphUart_tx  (txd1),
		    .gpio  (gpio),
		    .alarmout(LEDR[13]),
		    .triggerout(triggerout),
		    .wdogn(wdogn));

   assign LEDR[8]     = ~led8inv;
   
   assign GPIO[33] 	  = dsutx;
   assign LEDG[0]      = dsutx;
   
   assign dsurx        = GPIO[35];
   assign LEDG[1]      = GPIO[35];
   
   assign GPIO[31] = txd1;   
   assign LEDG[2]      = txd1;
   
   assign rxd1         = GPIO[29];
   assign LEDG[3]      = GPIO[29];
   
   assign LEDR[7:0]    = gpio;
   assign {GPIO[7],GPIO[6],GPIO[5],GPIO[4],GPIO[3],GPIO[2],GPIO[1],GPIO[0]} = gpio;

   assign {GPIO[11],GPIO[13],GPIO[15],GPIO[17]} = triggerout;
			
			

endmodule
