
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module LEON3_DE1(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// GPIO_0, GPIO_0 connect to GPIO Default //////////
	inout 		    [35:0]		GPIO
);

   wire [7:0] 				gpio;
   wire 					dsutx;
   wire 					dsurx;
   wire 					rxd1;
   wire 					txd1;
   wire [3:0] 				triggerout;
   wire 					wdogn;
   wire						led8inv;
   wire						led9inv;

	leon3mp top(.clk   (CLOCK_50),
		    .resetn(KEY[3]),
		    .errorn(led8inv),
		    .DebugUart_tx (dsutx),
		    .DebugUart_rx (dsurx),
//		    .dsuact(LEDR[17]),
		    .dsuen(SW[9]),
		    .dsubre (SW[8]),
		    .PeriphUart_rx  (rxd1),
		    .PeriphUart_tx  (txd1),
		    .gpio  (gpio),
		    .alarmout(GPIO[18]),
		    .triggerout(triggerout),
		    .wdogn(led9inv));

   assign LEDR[8]     = ~led8inv;
   
   assign GPIO[33] 	  = dsutx;
   assign LEDR[4]      = dsutx;
   
   assign dsurx        = GPIO[35];
   assign LEDR[5]      = GPIO[35];
   
   assign GPIO[31] = txd1;   
   assign LEDR[6]      = txd1;
   
   assign rxd1         = GPIO[29];
   assign LEDR[7]      = GPIO[29];  
   assign LEDR[9]	= ~led9inv;
   assign LEDR[3:0]    = gpio[3:0];
   assign {GPIO[7],GPIO[6],GPIO[5],GPIO[4],GPIO[3],GPIO[2],GPIO[1],GPIO[0]} = gpio;

   assign {GPIO[11],GPIO[13],GPIO[15],GPIO[17]} = triggerout;

endmodule